name: Release Artifacts

on:
  # release:
  #   types: [published]
  [pull_request]

permissions:
    packages: write
    
jobs:
  Build_and_Release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore --verbosity normal
    - name: Pack c#
      run: dotnet pack -c Release --no-build --output . IOInfoExtensions
    - name: Publish c# Module
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/TheSquirrelDev/index.json" --skip-duplicate
    - name: Publish PowerShell Module
      shell: pwsh
      run: |
        .\IOInfoExtensions.PowerShell\Copy-ModuleFiles.ps1 -BinaryOutputDirectory .\IOInfoExtensions\bin\Release\netstandard2.0 -ProjectDirectory .\IOInfoExtensions.PowerShell -ModuleRootDirectory .\Output -Verbose
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $repoName = "TheSquirrelDev"
        $url = "https://nuget.pkg.github.com/$repoName/index.json"
        Register-PSRepository -Name $repoName -SourceLocation $url -PublishLocation $url -InstallationPolicy Trusted -Verbose 
        Publish-Module -Path .\Output -Repository $repoName -NuGetApiKey ${{ secrets.GITHUB_TOKEN }}
